name: greetings

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

jobs:
    build:
        runs-on: ubuntu-latest
        container: python:3.9-slim
        
        steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: echos
          run : |
            echo "greetings from command line"
        
